# Generated by Django 3.2.3 on 2023-11-17 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20231117_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Название может содержать только буквы, цифры и пробелы.', regex='^[a-zA-Z0-9\\s]+$')], verbose_name='Название'),
        ),
    ]
