# Generated by Django 4.2.6 on 2023-11-16 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Имя может содержать только буквы и пробелы.', regex='^[a-zA-Zа-яА-ЯёЁ\\s]+$')], verbose_name='Имя'),
        ),
    ]
