# Generated by Django 4.2.6 on 2023-11-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('author')), _negated=True), name='check_not_self_subscribe'),
        ),
    ]
