# Generated by Django 3.2.3 on 2023-11-17 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Имя может содержать только буквы и пробелы.', regex='^[a-zA-Zа-яА-ЯёЁ]+$')], verbose_name='Имя'),
        ),
    ]
