# Generated by Django 3.2.3 on 2023-11-17 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Фамилия может содержать только буквы и пробелы.', regex='^[a-zA-Zа-яА-ЯёЁ]+$')], verbose_name='Фамилия'),
        ),
    ]
