# Generated by Django 3.2.3 on 2023-11-19 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20231119_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Эти данные могут содержать только буквы и пробелы.', regex='^[a-zA-Zа-яА-ЯёЁ]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Эти данные могут содержать только буквы и пробелы.', regex='^[a-zA-Zа-яА-ЯёЁ]+$')], verbose_name='Фамилия'),
        ),
    ]
